return {
    lsps = {
        "bashls",
        "clangd",
        "jsonls",
        "lua_ls",
        "marksman",
        "rust_analyzer",
        "sqls",
        "taplo",
        "vimls",
    },
    ts = {
        "bash",
        "c",
        "gitignore",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "norg",
        "rust",
        "sql",
        "toml",
        "regex",
    },
    null = {
        "stylua",
    },
}
