return {
    lsps = {
        "bashls",
        "clangd",
        "omnisharp",
        "jsonls",
        "lua_ls",
        "sqlls",
        "texlab",
        "ts_ls",
        "html",
        "cssls",
        "powershell_es",
        "angularls",
        "emmet_ls",
        "jdtls",
    },
    ts = {
        "bash",
        "c",
        "c_sharp",
        "json",
        "lua",
        "sql",
        "latex",
        "typescript",
        "html",
        "css",
        "gitignore",
        "markdown",
        "markdown_inline",
    },
}
