return {
    lsps = {
        "bashls",
        "clangd",
        "omnisharp",
        "jsonls",
        "lua_ls",
        "sqlls",
        "texlab",
        "tsserver",
        "html",
        "intelephense",
        "cssls",
        "powershell_es",
        "angularls",
        "lemminx",
    },
    ts = {
        "bash",
        "c",
        "c_sharp",
        "json",
        "lua",
        "sql",
        "latex",
        "typescript",
        "html",
        "css",
        "php",
        "xml",
        "gitignore",
    },
}
