return {
    lsps = {
        "bashls",
        "clangd",
        "omnisharp",
        "jsonls",
        "lua_ls",
        "sqls",
        "tsserver",
        "html",
        "ltex",
        "powershell_es",
        "angularls",
    },
    ts = {
        "bash",
        "c",
        "c_sharp",
        "json",
        "lua",
        "sql",
        "typescript",
        "html",
        "latex",
        "gitignore",
    },
}
